#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtWidgets/QMainWindow>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QVBoxLayout>

namespace Ui {
class MainWindow {
public:
    QStackedWidget *stackedWidget;
    QWidget *pageLogin;
    QComboBox *comboRole;
    QLineEdit *editUsername;
    QLineEdit *editPassword;
    QPushButton *btnLogin;
    QPushButton *btnSignup;
    QWidget *pageStudent;
    QPushButton *btnViewContentStudent;
    QPushButton *btnAddCourse;
    QPushButton *btnAddMarks;
    QPushButton *btnLogoutStudent;
    QWidget *pageFaculty;
    QPushButton *btnAddContentFaculty;
    QPushButton *btnLogoutFaculty;
    QWidget *pageAdmin;
    QPushButton *btnAddContentAdmin;
    QPushButton *btnDeleteContentAdmin;
    QPushButton *btnViewAllContentAdmin;
    QPushButton *btnLogoutAdmin;

    void setupUi(QMainWindow *MainWindow) {
        // This is a placeholder for the uic-generated code.
        // In practice, this file is generated by Qt's uic from MainWindow.ui.
    }
};
}

#endif // UI_MAINWINDOW_H